# Generated by Django 3.2.25 on 2025-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetree',
            name='title',
            field=models.CharField(default='Untitled Knowledge Tree', max_length=255),
        ),
    ]
