# Generated by Django 3.2.25 on 2025-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_knowledgetree_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgetree',
            options={'ordering': ['-created_at'], 'verbose_name': '知识点树', 'verbose_name_plural': '知识点树'},
        ),
        migrations.AlterField(
            model_name='knowledgetree',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='存储知识点的 JSON 数据，PostgreSQL 中会被存为 jsonb 类型'),
        ),
        migrations.AlterField(
            model_name='knowledgetree',
            name='title',
            field=models.CharField(default='Untitled Knowledge Tree', help_text='知识点树的名称', max_length=255),
        ),
    ]
